### ISSUE TITLE
Triton Build Step For NGINX May fail on Repeated Calls

### ISSUE THREAD

**Issue by jacobloveless** [autopilotpattern/hello-world#10]
Just an FYI but there may be an issue attempting to build on triton repeatedly with the repo. You will receive an  like:
docker-compose up
...
Building nginx
ERROR: Service 'nginx' failed to build: Build failed: No such image: 65172d404869e5f75638461c3731f8d322bf858565c01f8896e5540e796a4cd1 (req_id: XXXXXX-81d7-11e6-a492-a726593dff9c)

**Comment by tgross** [comment]
@jacobloveless this unfortunately appears to be an issue with `docker build` on Triton. You might make more progress with the problem if you open a Triton support case or (if you're using open source w/o a support plan) if you open a GitHub issue against https://github.com/joyent/sdc-docker
