### ISSUE TITLE
Permission denied reload-nginx.sh

### ISSUE THREAD

**Issue by mbbender** [autopilotpattern/hello-world#15]
For some reason I was getting an error that the reload-nginx.sh could not execute due to permission issues. I had to add a line `RUN chmod 777 /bin/reload-nginx.sh` in my build to get it to work.

**Comment by tgross** [comment]
The `reload-nginx.sh` in the repo has the `755` permission, which should be preserved by the `COPY` instruction. Where are you building the image and on what version of Docker?

**Comment by mbbender** [comment]
I was building locally on my Mac with Docker 1.12.3.  I was on osSierra which seemed to be causing lots of grief for some reason. I recently went back to 10.10.5. I'll give it another try later today if I can to see if does the same thing with fresh everything.

**Comment by mbbender** [comment]
Yeah, not sure why this happened. But after doing everything fresh it works as expected.
