### ISSUE TITLE
Cannot start service nginx

### ISSUE THREAD

**Issue by ndaidong** [autopilotpattern/hello-world#9]
Hi there, 

I got the following issue while trying to install hello-world on my local machine (LinuxMint 18):

![Imgur](http://i.imgur.com/38raeUg.png)

How I can fix it?
Thanks,
Dong

**Comment by geek** [comment]
@ndaidong the [docker-compose.yml](https://github.com/autopilotpattern/hello-world/blob/master/docker-compose.yml#L4) file is configured to map port 80 from the Nginx container to the host port 80. It looks like something is already using port 80 on the docker host. To workaround the issue please update the `-ports` entry to `"8000:80"` or something similar to map the `"HOST:CONTAINER"`.  Changing the mapped port will require you to connect to hello-world on whatever port you choose.

**Comment by ndaidong** [comment]
@geek Thank you. I've got it works by following your guide. 
(Issue will be marked resolved. Sorry for missing your reply.)
